server.port=8082
spring.application.name=product-service

spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# SpringDoc configuration
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
# This tells Spring Boot to trust the X-Forwarded-* headers from Traefik
server.forward-headers-strategy=framework

# Spring Cloud Stream configuration
spring.cloud.function.definition=reduceStock
spring.cloud.stream.bindings.reduceStock-in-0.destination=order-placed
spring.cloud.stream.bindings.reduceStock-in-0.group=product-service-group
spring.cloud.stream.rabbit.bindings.reduceStock-in-0.consumer.exchangeType=topic

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
