server.port=8083
spring.application.name=ordering-service

spring.datasource.url=jdbc:h2:mem:orderingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# SpringDoc configuration
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
# This tells Spring Boot to trust the X-Forward-* headers from Traefik
server.forward-headers-strategy=framework

# Feign Client URLs
app.user-service.url=http://user:8081
app.product-service.url=http://product:8082

# Spring Cloud Stream configuration
spring.cloud.function.definition=handleStockReserved;handleStockReservationFailed
spring.cloud.stream.bindings.orderPlaced-out-0.destination=order-placed
spring.cloud.stream.rabbit.bindings.orderPlaced-out-0.producer.exchangeType=topic

spring.cloud.stream.bindings.handleStockReserved-in-0.destination=stock-reserved
spring.cloud.stream.bindings.handleStockReserved-in-0.group=ordering-service-group
spring.cloud.stream.rabbit.bindings.handleStockReserved-in-0.consumer.exchangeType=topic

spring.cloud.stream.bindings.handleStockReservationFailed-in-0.destination=stock-reservation-failed
spring.cloud.stream.bindings.handleStockReservationFailed-in-0.group=ordering-service-group
spring.cloud.stream.rabbit.bindings.handleStockReservationFailed-in-0.consumer.exchangeType=topic

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
