server.port=8083
spring.application.name=ordering-service

spring.datasource.url=jdbc:h2:mem:orderingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# SpringDoc configuration
springdoc.swagger-ui.path=/swagger-ui/index.html
